In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [3]:
df=sns.load_dataset('mpg')

In [4]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [5]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [6]:
df.drop("name",axis=1,inplace=True)

In [7]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [8]:
df['horsepower'].median()

np.float64(93.5)

In [10]:
df['horsepower']=df['horsepower'].fillna(df['horsepower'].median())

In [11]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [14]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin           object
dtype: object

In [15]:
df['origin']

0         usa
1         usa
2         usa
3         usa
4         usa
        ...
393       usa
394    europe
395       usa
396       usa
397       usa
Name: origin, Length: 398, dtype: object

In [16]:
df['origin'].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [19]:
df['origin']=df['origin'].map({"usa":1,"japan":2,"europe":3})

In [20]:
df['origin'] =df['origin'].astype(int)

In [21]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin            int64
dtype: object

In [22]:
#separate x and y
X=df.drop('mpg',axis=1)
y=df['mpg']

In [23]:
X

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504,12.0,70,1
1,8,350.0,165.0,3693,11.5,70,1
2,8,318.0,150.0,3436,11.0,70,1
3,8,304.0,150.0,3433,12.0,70,1
4,8,302.0,140.0,3449,10.5,70,1
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
394,4,97.0,52.0,2130,24.6,82,3
395,4,135.0,84.0,2295,11.6,82,1
396,4,120.0,79.0,2625,18.6,82,1
397,4,119.0,82.0,2720,19.4,82,1

In [24]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [25]:
#train test split

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [28]:
X_train.shape,X_test.shape

((278, 7), (120, 7))

In [29]:
# smiple linea regression model 
from sklearn.linear_model import LinearRegression
regression_model=LinearRegression()

In [30]:
regression_model

LinearRegression()

In [31]:
regression_model.fit(X_train,y_train)

LinearRegression()

In [33]:
for i, col_name in enumerate(X_train.columns):
    print(f'The coefficient for {col_name} is {regression_model.coef_[i]}')

The coefficient for cylinders is -0.31761423027992997
The coefficient for displacement is 0.02623748259907894
The coefficient for horsepower is -0.018270764913124644
The coefficient for weight is -0.007487750398361904
The coefficient for acceleration is 0.050406734619713886
The coefficient for model_year is 0.8470951427061371
The coefficient for origin is 1.5190958387975042

In [34]:
#coefficient are relatively smaller , if one independent variable changes 
#slightly there will be not much difference in prediction 
#this is sometime is called smoother model

In [38]:
from sklearn.metrics import r2_score

y_pred_linear =regression_model.predict(X_test)
r2_linear= r2_score(y_test,y_pred_linear)

print(f"R square of linear regression {r2_linear}")

R square of linear regression 0.8348001123742284

In [40]:
# Ridge regression 
from sklearn.linear_model import Ridge
ridge_regression_model = Ridge(alpha=0.1)

ridge_regression_model.fit(X_train,y_train)


for i, col_name in enumerate(X_train.columns):
    print(f"The coefficient for {col_name} is {ridge_regression_model.coef_[i]}")

The coefficient for cylinders is -0.31700321010067906
The coefficient for displacement is 0.02621324975798342
The coefficient for horsepower is -0.018263252481449534
The coefficient for weight is -0.00748732605021309
The coefficient for acceleration is 0.050368969474425776
The coefficient for model_year is 0.8470062938903167
The coefficient for origin is 1.5174528285653937

In [41]:
# For Ridge Regression evaluation 
y_pred_ridge =ridge_regression_model.predict(X_test)
r2_ridge =r2_score(y_test,y_pred_ridge)

print(f"R-suared score for ridge Regression: {r2_ridge}")

R-suared score for ridge Regression: 0.8348084889168355

In [ ]:
# We dont see much variaation in coeff of rifge regression as compares to linear regression

In [44]:
from sklearn.linear_model import Lasso 
Lasso_ression_model= Lasso(alpha=0.5)
Lasso_ression_model.fit(X_train,y_train)

for i,col_name in enumerate (X_train.columns):
    print(f"The coefficient for {col_name} is {Lasso_ression_model.coef_[i]}")

The coefficient for cylinders is -0.0
The coefficient for displacement is 0.006208198888300358
The coefficient for horsepower is -0.011058382987169565
The coefficient for weight is -0.0069826731680230885
The coefficient for acceleration is 0.0
The coefficient for model_year is 0.744654952003819
The coefficient for origin is 0.0

In [45]:
#3 feature coefficient are 0, Lasso helps in feature selction

In [47]:
y_pred_lasso =Lasso_ression_model.predict(X_test)
r2_lasso =r2_score(y_test,y_pred_lasso)
print(f"R-squared score for Lasso Regression : {r2_lasso}")

R-squared score for Lasso Regression : 0.8277934716635555

In [48]:
from sklearn.linear_model import ElasticNet

ElasticNet_regression_model=ElasticNet(alpha=1,l1_ratio=0.5)
ElasticNet_regression_model.fit(X_train,y_train)

ElasticNet(alpha=1)

In [49]:
for i,col_name in enumerate(X_train.columns):
    print(f"The coefficient for {col_name} is {ElasticNet_regression_model.coef_[i]}")

The coefficient for cylinders is -0.0
The coefficient for displacement is 0.005888869953667563
The coefficient for horsepower is -0.012403874933570126
The coefficient for weight is -0.006934550516257631
The coefficient for acceleration is 0.0
The coefficient for model_year is 0.7133150744603874
The coefficient for origin is 0.0

In [51]:
y_pred_elastic_net =ElasticNet_regression_model.predict(X_test)

r2_elastic_net = r2_score(y_test,y_pred_elastic_net)

print(f"R-squares score for Elastic Net Regression : {r2_elastic_net}")

R-squares score for Elastic Net Regression : 0.8284840073256804